### ISSUE TITLE
Publish Path specified by Edit ROM or New project isn't respected

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#126]
When specifying a publish path, it isn't respected:
- the Edit ROM dialog show it, but it's empty when the project is created.
- the New Project dialogs show it, but it's either blank or relative to the app folder when the project is created.

Ensure that the publish path is preserved after project creation.

**Comment by essellejaye** [comment]
@ffhacksterex  In the case a publish path that's relative to the project, we'll have to also implement project-relative path support to accomplish that; is that already a separate issue?

**Comment by ffhacksterex** [comment]
@essellejaye No, we had something similar for *APP, I'll add a new one for this.
