### ISSUE TITLE
Add support for project-relative paths (e.g. *PRJ) for Publish path settings

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#127]
Similar to *APP, support project-relative paths in for the publish path.
Currently, there is no way to specify a path relative to the project.
This makes project portability more difficult, since absolute paths will be used for the files.

**Comment by essellejaye** [comment]
@ffhacksterex This is already happening, it just wasn't being invoked for the publish path.
