### ISSUE TITLE
Various controls (e.g. check boxes) don't trigger OK when pressing ENTER

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#129]
Normal check boxes and radio buttons will trigger the OK button action when ENTER is pressed.
However, many throughout the app don't do this.
Example:
- Tab to or click any of the check boxes on the Edit ROM and Create Project screens.
- Click ENTER, and nothing happens.

**Comment by essellejaye** [comment]
@ffhacksterex  Reopening, the change has an adverse effect on command buttons.
If we're not doing a full redesign, then I'll need to insert intermediary classes to handle the checks and radio buttons.
