### ISSUE TITLE
Icons do not scale when the desktop scale factor is changed

### ISSUE THREAD

**Issue by essellejaye** [ffhacksterex/FFHacksterEx#18]
Icons are always rendered at their 100% side, so when the Windows desktop scaling factor is set to a different value, the icons do not scale accordingly.
e.g. Set the Desktop to 150%, and the icon appear noticeably smaller on every dialog.

**Comment by essellejaye** [comment]
To handle this, we'll need to use these WINAPI functions:
MonitorFromWindow on the current dialog,
then GetScaleFactorForMonitor to get the scale to use for drawing.
[see GetScaleFactorForMonitor](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor)

We'll also need to handle a couple of events:
WM_WINDOWPOSCHANGED on the base window,
and RegisterScaleChangeEvent on the base app.
[see RegisterScaleChangeEvent](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-registerscalechangeevent)

**Comment by essellejaye** [comment]
Investigating this uncovered that the x64 build has the High DPI-aware setting turned on in the application manifest. The app doesn't handle scaling, but since this system prevents the system from doing it, the result is that dynamically drawn graphics aren't scaled (maps, sprites, spells, weapons, etc.).
The x86 build doesn't use it and isn't affected.

An easier fix than trying what's in my previous comment is to disable the DPI-aware settings.
That should fix the icons, maps, sprites, etc..

**Comment by ffhacksterex** [comment]
Let's patch this for 0.9.7.1
