### ISSUE TITLE
Assembly Project - Ensure that FF1.nes is removed regardless of compile result

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#33]
Currently, a batch file is used internally to compile the NES image.
However, it targets a temp file in the asm/ folder, then copies that to the main directory.
- Since the batch file takes a full pathname to a file as a parameter, pass the work ROM file path to the batch file instead of 'ff1.nes'.

**Comment by essellejaye** [comment]
I think the reason for this is that the FF1.nes file can hang around, allowing it to be inadvertently included in zip files.
If that's the case, then instead of changing how the batch file works, we could just ensure that we delete FF1.nes no matter the result of the compilation.
